# .harness/environments/pcf.yaml
# DEV
environment:
  name: PCF_Dev
  identifier: PCF_Dev
  orgIdentifier: default
  projectIdentifier: ucd2harnessmigration
  type: PreProduction
  tags:
    PCF_Deployment: "true"
---
infrastructureDefinition:
  name: pcf_dev_space
  identifier: pcf_dev_space
  orgIdentifier: default
  projectIdentifier: ucd2harnessmigration
  environmentRef: PCF_Dev
  type: TAS
  spec:
    connectorRef: my_pcf_connector   # CF/TAS connector in Harness
    organization: my-org             # CF/TAS org
    space: dev                       # CF/TAS space
    releaseName: webapp-dev

---
# QA
environment:
  name: PCF_QA
  identifier: PCF_QA
  orgIdentifier: default
  projectIdentifier: ucd2harnessmigration
  type: PreProduction
  tags:
    PCF_Deployment: "true"
---
infrastructureDefinition:
  name: pcf_qa_space
  identifier: pcf_qa_space
  orgIdentifier: default
  projectIdentifier: ucd2harnessmigration
  environmentRef: PCF_QA
  type: TAS
  spec:
    connectorRef: my_pcf_connector
    organization: my-org
    space: qa
    releaseName: webapp-qa

---
# PROD
environment:
  name: PCF_Prod
  identifier: PCF_Prod
  orgIdentifier: default
  projectIdentifier: ucd2harnessmigration
  type: Production
  tags:
    PCF_Deployment: "true"
---
infrastructureDefinition:
  name: pcf_prod_space
  identifier: pcf_prod_space
  orgIdentifier: default
  projectIdentifier: ucd2harnessmigration
  environmentRef: PCF_Prod
  type: TAS
  spec:
    connectorRef: my_pcf_connector
    organization: my-org
    space: prod
    releaseName: webapp
